### ISSUE TITLE
Single quotes vs Double quotes on lang property of script tag

### ISSUE THREAD

**Issue by HenBK** [ExEr7um/vue3-vscode-snippets#49]
Hi there, I wanted to thank you for making this extension, it was very annoying to manually move the script tag to the top of the file each time I generated a new single file component using `vbase`, so thanks a lot.

I opened this issue because I wanted to suggest the use of double quotes for the value of the `lang` property in the `<script>` tag, so it goes from `<script setup lang='ts'>` to `<script setup lang="ts">`

Even though this is a small change and doesn't make much of a difference in terms of functionality I do think it would be beneficial since it would help to keep consistency considering that the extension currently generates the `<style>` tag in this way `<style lang="scss">` and most html property values tend to be set with double quotes by other code generation tools

Best regards!

**Comment by ExEr7um** [comment]
Thanks for the issue. Yes, I think we should make it consistent with double quotes. PRs are welcome!

**Comment by HenBK** [comment]
Opened the [pull request](https://github.com/ExEr7um/vue3-vscode-snippets/pull/50) :)

I'm not entirely sure if I updated the CHANGELOG correctly so let me know if there is any changes you would like me to make, happy to help!
